---
# Add Syncthing stable channel sources.
- name: Add Syncthing source repo.
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Add GNU PGP Key.
  become: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Set repo source preference.
  become: yes
  copy:
    src: syncthing
    dest: '{{ pref_loc }}'
  